-- GymFitness MySQL 8.0+ schema
-- CHAR(36) values are generated by the application before INSERT.

CREATE DATABASE IF NOT EXISTS gymfitness
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

USE gymfitness;

SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET time_zone = '+00:00';

-- ============================================================
-- Organization, authentication and profiles
-- ============================================================

CREATE TABLE branches (
  id CHAR(36) PRIMARY KEY,
  code VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  address_line TEXT NOT NULL,
  phone VARCHAR(30),
  timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Bangkok',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE users (
  id CHAR(36) PRIMARY KEY,
  email VARCHAR(254) NOT NULL UNIQUE,
  phone VARCHAR(30) UNIQUE,
  password_hash TEXT NOT NULL,
  role VARCHAR(16) NOT NULL CHECK (role IN ('ADMIN', 'USER', 'PT')),
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'INACTIVE')),
  email_verified_at DATETIME(6),
  phone_verified_at DATETIME(6),
  last_login_at DATETIME(6),
  failed_login_count INTEGER NOT NULL DEFAULT 0 CHECK (failed_login_count >= 0),
  locked_until DATETIME(6),
  two_factor_secret_encrypted TEXT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_users_role_status ON users (role, status);

CREATE TABLE file_assets (
  id CHAR(36) PRIMARY KEY,
  owner_user_id CHAR(36),
  storage_key VARCHAR(512) NOT NULL UNIQUE,
  original_name TEXT NOT NULL,
  content_type VARCHAR(120) NOT NULL,
  size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
  visibility VARCHAR(12) NOT NULL DEFAULT 'PRIVATE'
    CHECK (visibility IN ('PRIVATE', 'PUBLIC')),
  checksum_sha256 CHAR(64),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  CONSTRAINT fk_file_assets_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE user_profiles (
  user_id CHAR(36) PRIMARY KEY,
  full_name VARCHAR(150) NOT NULL,
  avatar_file_id CHAR(36),
  date_of_birth DATE,
  gender VARCHAR(16) CHECK (gender IS NULL OR gender IN ('MALE', 'FEMALE', 'OTHER')),
  height_cm NUMERIC(5,2) CHECK (height_cm IS NULL OR height_cm BETWEEN 50 AND 300),
  weight_kg NUMERIC(5,2) CHECK (weight_kg IS NULL OR weight_kg BETWEEN 15 AND 500),
  experience_level VARCHAR(20)
    CHECK (experience_level IS NULL OR experience_level IN ('BEGINNER', 'BASIC', 'INTERMEDIATE', 'ADVANCED')),
  fitness_goal VARCHAR(24)
    CHECK (fitness_goal IS NULL OR fitness_goal IN ('WEIGHT_LOSS', 'MUSCLE_GAIN', 'GENERAL_HEALTH', 'FLEXIBILITY')),
  weekly_training_sessions SMALLINT CHECK (weekly_training_sessions IS NULL OR weekly_training_sessions BETWEEN 1 AND 14),
  emergency_contact_name VARCHAR(150),
  emergency_contact_phone VARCHAR(30),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CONSTRAINT fk_user_profiles_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_user_profiles_avatar_file_id FOREIGN KEY (avatar_file_id) REFERENCES file_assets(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE user_addresses (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  label VARCHAR(60),
  recipient_name VARCHAR(150) NOT NULL,
  recipient_phone VARCHAR(30) NOT NULL,
  province VARCHAR(100) NOT NULL,
  district VARCHAR(100) NOT NULL,
  ward VARCHAR(100) NOT NULL,
  address_line TEXT NOT NULL,
  delivery_note TEXT,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CONSTRAINT fk_user_addresses_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_user_addresses_user ON user_addresses (user_id, is_default, deleted_at);

CREATE TABLE refresh_tokens (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  token_digest CHAR(64) NOT NULL UNIQUE,
  jwt_id CHAR(36) NOT NULL UNIQUE,
  expires_at DATETIME(6) NOT NULL,
  revoked_at DATETIME(6),
  replaced_by_token_id CHAR(36),
  ip_address VARCHAR(45),
  user_agent TEXT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CHECK (expires_at > created_at),
  CONSTRAINT fk_refresh_tokens_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_refresh_tokens_replaced_by_token_id FOREIGN KEY (replaced_by_token_id) REFERENCES refresh_tokens(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_refresh_tokens_user_active
  ON refresh_tokens (user_id, expires_at);

CREATE TABLE password_reset_tokens (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  token_digest CHAR(64) NOT NULL UNIQUE,
  expires_at DATETIME(6) NOT NULL,
  used_at DATETIME(6),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CHECK (expires_at > created_at),
  CONSTRAINT fk_password_reset_tokens_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_password_reset_user_active
  ON password_reset_tokens (user_id, expires_at);

CREATE TABLE members (
  id CHAR(36) PRIMARY KEY,
  member_code VARCHAR(30) NOT NULL UNIQUE,
  user_id CHAR(36) UNIQUE,
  home_branch_id CHAR(36),
  full_name VARCHAR(150) NOT NULL,
  email VARCHAR(254),
  phone VARCHAR(30),
  joined_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE', 'SUSPENDED', 'INACTIVE')),
  notes TEXT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CONSTRAINT fk_members_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_members_home_branch_id FOREIGN KEY (home_branch_id) REFERENCES branches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_members_name ON members (full_name);
CREATE INDEX idx_members_status ON members (status);
CREATE INDEX idx_members_branch ON members (home_branch_id);

CREATE TABLE trainer_profiles (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL UNIQUE,
  employee_code VARCHAR(30) NOT NULL UNIQUE,
  branch_id CHAR(36),
  bio TEXT,
  certifications TEXT,
  hourly_rate NUMERIC(14,2) NOT NULL DEFAULT 200000 CHECK (hourly_rate >= 0),
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE', 'ON_LEAVE', 'INACTIVE')),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CONSTRAINT fk_trainer_profiles_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_trainer_profiles_branch_id FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE trainer_specialties (
  trainer_id CHAR(36) NOT NULL,
  specialty VARCHAR(24) NOT NULL
    CHECK (specialty IN ('GYM', 'YOGA', 'WEIGHT_LOSS', 'MUSCLE_GAIN', 'REHABILITATION', 'FLEXIBILITY')),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (trainer_id, specialty),
  CONSTRAINT fk_trainer_specialties_trainer_id FOREIGN KEY (trainer_id) REFERENCES trainer_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================
-- Payments, membership plans and subscriptions
-- ============================================================

CREATE TABLE payments (
  id CHAR(36) PRIMARY KEY,
  payment_number VARCHAR(40) NOT NULL UNIQUE,
  member_id CHAR(36),
  purpose VARCHAR(24) NOT NULL
    CHECK (purpose IN ('MEMBERSHIP', 'PT_CREDIT', 'PRODUCT_ORDER')),
  amount NUMERIC(14,2) NOT NULL CHECK (amount >= 0),
  currency CHAR(3) NOT NULL DEFAULT 'VND',
  method VARCHAR(20) NOT NULL DEFAULT 'QR'
    CHECK (method IN ('QR', 'CASH', 'BANK_TRANSFER', 'CARD')),
  status VARCHAR(16) NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'VOID')),
  provider VARCHAR(50),
  external_reference VARCHAR(150),
  idempotency_key VARCHAR(100) NOT NULL UNIQUE,
  qr_payload TEXT,
  qr_expires_at DATETIME(6),
  paid_at DATETIME(6),
  failure_reason TEXT,
  created_by CHAR(36),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CHECK ((status = 'PAID' AND paid_at IS NOT NULL) OR status <> 'PAID'),
  CONSTRAINT fk_payments_member_id FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE SET NULL,
  CONSTRAINT fk_payments_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX uq_payments_provider_reference ON payments (provider, external_reference);
CREATE INDEX idx_payments_member_created ON payments (member_id, created_at DESC);
CREATE INDEX idx_payments_status_created ON payments (status, created_at DESC);

CREATE TABLE payment_events (
  id CHAR(36) PRIMARY KEY,
  payment_id CHAR(36),
  provider VARCHAR(50) NOT NULL,
  provider_event_id VARCHAR(150) NOT NULL,
  event_type VARCHAR(80) NOT NULL,
  signature_valid BOOLEAN NOT NULL DEFAULT FALSE,
  payload JSON NOT NULL,
  processed_at DATETIME(6),
  error_message TEXT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE (provider, provider_event_id),
  CONSTRAINT fk_payment_events_payment_id FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE membership_plans (
  id CHAR(36) PRIMARY KEY,
  code VARCHAR(40) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  activity_type VARCHAR(12) NOT NULL CHECK (activity_type IN ('GYM', 'YOGA')),
  description TEXT,
  duration_months SMALLINT CHECK (duration_months IS NULL OR duration_months > 0),
  duration_days SMALLINT CHECK (duration_days IS NULL OR duration_days > 0),
  price NUMERIC(14,2) NOT NULL CHECK (price >= 0),
  currency CHAR(3) NOT NULL DEFAULT 'VND',
  max_visits INTEGER CHECK (max_visits IS NULL OR max_visits > 0),
  freeze_days_allowed SMALLINT NOT NULL DEFAULT 0 CHECK (freeze_days_allowed >= 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CHECK ((duration_months IS NOT NULL) + (duration_days IS NOT NULL) = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_membership_plans_activity_active
  ON membership_plans (activity_type, is_active);

CREATE TABLE membership_subscriptions (
  id CHAR(36) PRIMARY KEY,
  member_id CHAR(36) NOT NULL,
  plan_id CHAR(36) NOT NULL,
  payment_id CHAR(36) UNIQUE,
  renewed_from_id CHAR(36),
  start_at DATETIME(6),
  end_at DATETIME(6),
  status VARCHAR(16) NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'ACTIVE', 'FROZEN', 'EXPIRED', 'CANCELLED')),
  remaining_visits INTEGER CHECK (remaining_visits IS NULL OR remaining_visits >= 0),
  frozen_from DATETIME(6),
  frozen_until DATETIME(6),
  cancelled_at DATETIME(6),
  cancellation_reason TEXT,
  created_by CHAR(36),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CHECK (end_at IS NULL OR start_at IS NOT NULL),
  CHECK (end_at IS NULL OR end_at > start_at),
  CHECK (frozen_until IS NULL OR (frozen_from IS NOT NULL AND frozen_until > frozen_from)),
  CHECK (cancelled_at IS NULL OR status = 'CANCELLED'),
  CONSTRAINT fk_membership_subscriptions_member_id FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE RESTRICT,
  CONSTRAINT fk_membership_subscriptions_plan_id FOREIGN KEY (plan_id) REFERENCES membership_plans(id) ON DELETE RESTRICT,
  CONSTRAINT fk_membership_subscriptions_payment_id FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE RESTRICT,
  CONSTRAINT fk_membership_subscriptions_renewed_from_id FOREIGN KEY (renewed_from_id) REFERENCES membership_subscriptions(id) ON DELETE SET NULL,
  CONSTRAINT fk_membership_subscriptions_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_subscriptions_member_status
  ON membership_subscriptions (member_id, status, end_at DESC);
CREATE INDEX idx_subscriptions_expiry
  ON membership_subscriptions (status, end_at, deleted_at);

CREATE TABLE subscription_status_history (
  id CHAR(36) PRIMARY KEY,
  subscription_id CHAR(36) NOT NULL,
  from_status VARCHAR(16),
  to_status VARCHAR(16) NOT NULL
    CHECK (to_status IN ('PENDING', 'ACTIVE', 'FROZEN', 'EXPIRED', 'CANCELLED')),
  reason TEXT,
  changed_by CHAR(36),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_subscription_status_history_subscription_id FOREIGN KEY (subscription_id) REFERENCES membership_subscriptions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_subscription_status_history_changed_by FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_subscription_history_subscription
  ON subscription_status_history (subscription_id, created_at DESC);

CREATE TABLE subscription_freeze_history (
  id CHAR(36) PRIMARY KEY,
  subscription_id CHAR(36) NOT NULL,
  frozen_from DATETIME(6) NOT NULL,
  frozen_until DATETIME(6) NOT NULL,
  days_granted SMALLINT NOT NULL CHECK (days_granted > 0),
  reason TEXT,
  created_by CHAR(36),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CHECK (frozen_until > frozen_from),
  CONSTRAINT fk_subscription_freeze_history_subscription_id FOREIGN KEY (subscription_id) REFERENCES membership_subscriptions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_subscription_freeze_history_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================
-- Training schedules and facility check-in
-- ============================================================

CREATE TABLE workout_schedule_entries (
  id CHAR(36) PRIMARY KEY,
  member_id CHAR(36) NOT NULL,
  subscription_id CHAR(36) NOT NULL,
  activity_type VARCHAR(12) NOT NULL CHECK (activity_type IN ('GYM', 'YOGA')),
  scheduled_date DATE NOT NULL,
  start_time TIME,
  end_time TIME,
  entry_type VARCHAR(20) NOT NULL
    CHECK (entry_type IN ('WORKOUT', 'REST', 'CLASS', 'PT_SESSION')),
  title VARCHAR(160) NOT NULL,
  description TEXT,
  status VARCHAR(16) NOT NULL DEFAULT 'PLANNED'
    CHECK (status IN ('PLANNED', 'COMPLETED', 'SKIPPED', 'CANCELLED')),
  source VARCHAR(16) NOT NULL DEFAULT 'SYSTEM'
    CHECK (source IN ('SYSTEM', 'USER', 'PT', 'ADMIN')),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CHECK (end_time IS NULL OR start_time IS NOT NULL),
  CHECK (end_time IS NULL OR end_time > start_time),
  CONSTRAINT fk_workout_schedule_entries_member_id FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE RESTRICT,
  CONSTRAINT fk_workout_schedule_entries_subscription_id FOREIGN KEY (subscription_id) REFERENCES membership_subscriptions(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_workout_schedule_member_date
  ON workout_schedule_entries (member_id, scheduled_date);
CREATE INDEX idx_workout_schedule_subscription
  ON workout_schedule_entries (subscription_id, scheduled_date);

CREATE TABLE qr_nonces (
  id CHAR(36) PRIMARY KEY,
  nonce_hash CHAR(64) NOT NULL UNIQUE,
  member_id CHAR(36) NOT NULL,
  subscription_id CHAR(36) NOT NULL,
  issued_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  expires_at DATETIME(6) NOT NULL,
  used_at DATETIME(6),
  revoked_at DATETIME(6),
  CHECK (expires_at > issued_at),
  CONSTRAINT fk_qr_nonces_member_id FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE RESTRICT,
  CONSTRAINT fk_qr_nonces_subscription_id FOREIGN KEY (subscription_id) REFERENCES membership_subscriptions(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_qr_nonces_expiry ON qr_nonces (expires_at);

CREATE TABLE check_ins (
  id CHAR(36) PRIMARY KEY,
  member_id CHAR(36) NOT NULL,
  subscription_id CHAR(36) NOT NULL,
  branch_id CHAR(36),
  qr_nonce_id CHAR(36) UNIQUE,
  check_in_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  check_out_at DATETIME(6),
  method VARCHAR(12) NOT NULL CHECK (method IN ('QR', 'MANUAL')),
  location TEXT,
  created_by CHAR(36),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CHECK (check_out_at IS NULL OR check_out_at > check_in_at),
  CHECK ((method = 'QR' AND qr_nonce_id IS NOT NULL) OR method = 'MANUAL'),
  CONSTRAINT fk_check_ins_member_id FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE RESTRICT,
  CONSTRAINT fk_check_ins_subscription_id FOREIGN KEY (subscription_id) REFERENCES membership_subscriptions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_check_ins_branch_id FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL,
  CONSTRAINT fk_check_ins_qr_nonce_id FOREIGN KEY (qr_nonce_id) REFERENCES qr_nonces(id) ON DELETE RESTRICT,
  CONSTRAINT fk_check_ins_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_check_ins_member_time ON check_ins (member_id, check_out_at, deleted_at, check_in_at DESC);
CREATE INDEX idx_check_ins_branch_time ON check_ins (branch_id, check_in_at DESC);

-- ============================================================
-- PT credit wallet, availability and bookings
-- ============================================================

CREATE TABLE pt_credit_accounts (
  id CHAR(36) PRIMARY KEY,
  member_id CHAR(36) NOT NULL UNIQUE,
  purchased_sessions INTEGER NOT NULL DEFAULT 0 CHECK (purchased_sessions >= 0),
  reserved_sessions INTEGER NOT NULL DEFAULT 0 CHECK (reserved_sessions >= 0),
  used_sessions INTEGER NOT NULL DEFAULT 0 CHECK (used_sessions >= 0),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CHECK (purchased_sessions >= reserved_sessions + used_sessions),
  CONSTRAINT fk_pt_credit_accounts_member_id FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE pt_credit_purchases (
  id CHAR(36) PRIMARY KEY,
  credit_account_id CHAR(36) NOT NULL,
  payment_id CHAR(36) NOT NULL UNIQUE,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(14,2) NOT NULL CHECK (unit_price >= 0),
  status VARCHAR(16) NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'CREDITED', 'REFUNDED', 'VOID')),
  credited_at DATETIME(6),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CHECK ((status = 'CREDITED' AND credited_at IS NOT NULL) OR status <> 'CREDITED'),
  CONSTRAINT fk_pt_credit_purchases_credit_account_id FOREIGN KEY (credit_account_id) REFERENCES pt_credit_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pt_credit_purchases_payment_id FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE trainer_availability (
  id CHAR(36) PRIMARY KEY,
  trainer_id CHAR(36) NOT NULL,
  branch_id CHAR(36),
  start_at DATETIME(6) NOT NULL,
  end_at DATETIME(6) NOT NULL,
  status VARCHAR(16) NOT NULL CHECK (status IN ('AVAILABLE', 'BUSY')),
  recurrence_rule TEXT,
  note TEXT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CHECK (end_at > start_at),
  CONSTRAINT fk_trainer_availability_trainer_id FOREIGN KEY (trainer_id) REFERENCES trainer_profiles(id) ON DELETE RESTRICT,
  CONSTRAINT fk_trainer_availability_branch_id FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_trainer_availability_search
  ON trainer_availability (trainer_id, start_at, end_at, status);

CREATE TABLE pt_bookings (
  id CHAR(36) PRIMARY KEY,
  booking_number VARCHAR(40) NOT NULL UNIQUE,
  member_id CHAR(36) NOT NULL,
  trainer_id CHAR(36) NOT NULL,
  subscription_id CHAR(36) NOT NULL,
  credit_account_id CHAR(36) NOT NULL,
  availability_id CHAR(36) NOT NULL,
  schedule_entry_id CHAR(36),
  activity_type VARCHAR(12) NOT NULL CHECK (activity_type IN ('GYM', 'YOGA')),
  start_at DATETIME(6) NOT NULL,
  end_at DATETIME(6) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'REQUESTED'
    CHECK (status IN ('REQUESTED', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'EXPIRED', 'COMPLETED', 'NO_SHOW')),
  rejection_reason TEXT,
  cancellation_reason TEXT,
  requested_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  response_due_at DATETIME(6),
  responded_at DATETIME(6),
  completed_at DATETIME(6),
  notes TEXT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CHECK (end_at > start_at),
  CHECK (response_due_at IS NULL OR response_due_at > requested_at),
  CHECK (status <> 'REJECTED' OR NULLIF(TRIM(rejection_reason), '') IS NOT NULL),
  CHECK (status <> 'COMPLETED' OR completed_at IS NOT NULL),
  CONSTRAINT fk_pt_bookings_member_id FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pt_bookings_trainer_id FOREIGN KEY (trainer_id) REFERENCES trainer_profiles(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pt_bookings_subscription_id FOREIGN KEY (subscription_id) REFERENCES membership_subscriptions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pt_bookings_credit_account_id FOREIGN KEY (credit_account_id) REFERENCES pt_credit_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pt_bookings_availability_id FOREIGN KEY (availability_id) REFERENCES trainer_availability(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pt_bookings_schedule_entry_id FOREIGN KEY (schedule_entry_id) REFERENCES workout_schedule_entries(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_pt_bookings_trainer_status_time
  ON pt_bookings (trainer_id, status, start_at);
CREATE INDEX idx_pt_bookings_member_status_time
  ON pt_bookings (member_id, status, start_at);
CREATE INDEX idx_pt_bookings_pending_expiry
  ON pt_bookings (status, response_due_at, deleted_at);

CREATE TABLE pt_credit_ledger (
  id CHAR(36) PRIMARY KEY,
  credit_account_id CHAR(36) NOT NULL,
  purchase_id CHAR(36),
  booking_id CHAR(36),
  transaction_type VARCHAR(16) NOT NULL
    CHECK (transaction_type IN ('PURCHASE', 'RESERVE', 'RELEASE', 'CONSUME', 'REFUND', 'ADJUST')),
  purchased_delta INTEGER NOT NULL DEFAULT 0,
  reserved_delta INTEGER NOT NULL DEFAULT 0,
  used_delta INTEGER NOT NULL DEFAULT 0,
  purchased_balance INTEGER NOT NULL CHECK (purchased_balance >= 0),
  reserved_balance INTEGER NOT NULL CHECK (reserved_balance >= 0),
  used_balance INTEGER NOT NULL CHECK (used_balance >= 0),
  idempotency_key VARCHAR(100) NOT NULL UNIQUE,
  reason TEXT,
  created_by CHAR(36),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CHECK (purchased_delta <> 0 OR reserved_delta <> 0 OR used_delta <> 0),
  CHECK (purchased_balance >= reserved_balance + used_balance),
  CONSTRAINT fk_pt_credit_ledger_credit_account_id FOREIGN KEY (credit_account_id) REFERENCES pt_credit_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pt_credit_ledger_purchase_id FOREIGN KEY (purchase_id) REFERENCES pt_credit_purchases(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pt_credit_ledger_booking_id FOREIGN KEY (booking_id) REFERENCES pt_bookings(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pt_credit_ledger_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_pt_credit_ledger_account_time
  ON pt_credit_ledger (credit_account_id, created_at DESC);
CREATE INDEX idx_pt_credit_ledger_booking ON pt_credit_ledger (booking_id);

-- ============================================================
-- Group classes
-- ============================================================

CREATE TABLE rooms (
  id CHAR(36) PRIMARY KEY,
  branch_id CHAR(36) NOT NULL,
  code VARCHAR(30) NOT NULL,
  name VARCHAR(100) NOT NULL,
  capacity INTEGER NOT NULL CHECK (capacity > 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  UNIQUE (branch_id, code),
  CONSTRAINT fk_rooms_branch_id FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE class_types (
  id CHAR(36) PRIMARY KEY,
  code VARCHAR(40) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  activity_type VARCHAR(12) NOT NULL CHECK (activity_type IN ('GYM', 'YOGA')),
  description TEXT,
  duration_minutes SMALLINT NOT NULL CHECK (duration_minutes > 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE class_sessions (
  id CHAR(36) PRIMARY KEY,
  class_type_id CHAR(36) NOT NULL,
  trainer_id CHAR(36) NOT NULL,
  room_id CHAR(36) NOT NULL,
  start_at DATETIME(6) NOT NULL,
  end_at DATETIME(6) NOT NULL,
  capacity INTEGER NOT NULL CHECK (capacity > 0),
  cancellation_deadline_at DATETIME(6),
  status VARCHAR(16) NOT NULL DEFAULT 'SCHEDULED'
    CHECK (status IN ('SCHEDULED', 'CANCELLED', 'COMPLETED')),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CHECK (end_at > start_at),
  CHECK (cancellation_deadline_at IS NULL OR cancellation_deadline_at < start_at),
  CONSTRAINT fk_class_sessions_class_type_id FOREIGN KEY (class_type_id) REFERENCES class_types(id) ON DELETE RESTRICT,
  CONSTRAINT fk_class_sessions_trainer_id FOREIGN KEY (trainer_id) REFERENCES trainer_profiles(id) ON DELETE RESTRICT,
  CONSTRAINT fk_class_sessions_room_id FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_class_sessions_start_status ON class_sessions (start_at, status);

CREATE TABLE class_bookings (
  id CHAR(36) PRIMARY KEY,
  session_id CHAR(36) NOT NULL,
  member_id CHAR(36) NOT NULL,
  subscription_id CHAR(36) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'BOOKED'
    CHECK (status IN ('BOOKED', 'WAITLISTED', 'CANCELLED', 'ATTENDED', 'NO_SHOW')),
  waitlist_position INTEGER CHECK (waitlist_position IS NULL OR waitlist_position > 0),
  booked_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  cancelled_at DATETIME(6),
  check_in_at DATETIME(6),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  UNIQUE (session_id, member_id),
  CHECK ((status = 'WAITLISTED' AND waitlist_position IS NOT NULL) OR status <> 'WAITLISTED'),
  CHECK (cancelled_at IS NULL OR status = 'CANCELLED'),
  CONSTRAINT fk_class_bookings_session_id FOREIGN KEY (session_id) REFERENCES class_sessions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_class_bookings_member_id FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE RESTRICT,
  CONSTRAINT fk_class_bookings_subscription_id FOREIGN KEY (subscription_id) REFERENCES membership_subscriptions(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_class_bookings_session_status
  ON class_bookings (session_id, status, waitlist_position);
CREATE INDEX idx_class_bookings_member ON class_bookings (member_id, booked_at DESC);

-- ============================================================
-- Product catalog, inventory, cart and orders
-- ============================================================

CREATE TABLE product_categories (
  id CHAR(36) PRIMARY KEY,
  parent_id CHAR(36),
  code VARCHAR(40) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  activity_type VARCHAR(12) CHECK (activity_type IS NULL OR activity_type IN ('GYM', 'YOGA')),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_product_categories_parent_id FOREIGN KEY (parent_id) REFERENCES product_categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE products (
  id CHAR(36) PRIMARY KEY,
  category_id CHAR(36),
  slug VARCHAR(180) NOT NULL UNIQUE,
  name VARCHAR(180) NOT NULL,
  description TEXT,
  brand VARCHAR(100),
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE')),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CONSTRAINT fk_products_category_id FOREIGN KEY (category_id) REFERENCES product_categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_products_category_status ON products (category_id, status);
CREATE INDEX idx_products_name ON products (name);

CREATE TABLE product_variants (
  id CHAR(36) PRIMARY KEY,
  product_id CHAR(36) NOT NULL,
  sku VARCHAR(60) NOT NULL UNIQUE,
  name VARCHAR(120),
  attributes JSON NOT NULL DEFAULT (JSON_OBJECT()),
  price NUMERIC(14,2) NOT NULL CHECK (price >= 0),
  compare_at_price NUMERIC(14,2),
  currency CHAR(3) NOT NULL DEFAULT 'VND',
  stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
  reserved_quantity INTEGER NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CHECK (stock_quantity >= reserved_quantity),
  CHECK (compare_at_price IS NULL OR compare_at_price >= price),
  CONSTRAINT fk_product_variants_product_id FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_product_variants_product ON product_variants (product_id);

CREATE TABLE product_images (
  id CHAR(36) PRIMARY KEY,
  product_id CHAR(36) NOT NULL,
  file_asset_id CHAR(36) NOT NULL,
  alt_text VARCHAR(200),
  sort_order SMALLINT NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE (product_id, file_asset_id),
  CONSTRAINT fk_product_images_product_id FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_images_file_asset_id FOREIGN KEY (file_asset_id) REFERENCES file_assets(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE carts (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL UNIQUE,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_carts_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE cart_items (
  id CHAR(36) PRIMARY KEY,
  cart_id CHAR(36) NOT NULL,
  variant_id CHAR(36) NOT NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE (cart_id, variant_id),
  CONSTRAINT fk_cart_items_cart_id FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE CASCADE,
  CONSTRAINT fk_cart_items_variant_id FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE orders (
  id CHAR(36) PRIMARY KEY,
  order_number VARCHAR(40) NOT NULL UNIQUE,
  user_id CHAR(36) NOT NULL,
  member_id CHAR(36),
  payment_id CHAR(36) UNIQUE,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING_PAYMENT'
    CHECK (status IN ('PENDING_PAYMENT', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED')),
  subtotal NUMERIC(14,2) NOT NULL CHECK (subtotal >= 0),
  discount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
  shipping_fee NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (shipping_fee >= 0),
  total NUMERIC(14,2) NOT NULL CHECK (total >= 0),
  currency CHAR(3) NOT NULL DEFAULT 'VND',
  placed_at DATETIME(6),
  cancelled_at DATETIME(6),
  cancellation_reason TEXT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CHECK (total = subtotal - discount + shipping_fee),
  CHECK (cancelled_at IS NULL OR status = 'CANCELLED'),
  CONSTRAINT fk_orders_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_orders_member_id FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE SET NULL,
  CONSTRAINT fk_orders_payment_id FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_orders_user_created ON orders (user_id, created_at DESC);
CREATE INDEX idx_orders_status_created ON orders (status, created_at DESC);

CREATE TABLE order_addresses (
  order_id CHAR(36) PRIMARY KEY,
  source_address_id CHAR(36),
  recipient_name VARCHAR(150) NOT NULL,
  recipient_phone VARCHAR(30) NOT NULL,
  province VARCHAR(100) NOT NULL,
  district VARCHAR(100) NOT NULL,
  ward VARCHAR(100) NOT NULL,
  address_line TEXT NOT NULL,
  delivery_note TEXT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_order_addresses_order_id FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
  CONSTRAINT fk_order_addresses_source_address_id FOREIGN KEY (source_address_id) REFERENCES user_addresses(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE order_items (
  id CHAR(36) PRIMARY KEY,
  order_id CHAR(36) NOT NULL,
  variant_id CHAR(36),
  sku_snapshot VARCHAR(60) NOT NULL,
  product_name_snapshot VARCHAR(180) NOT NULL,
  variant_snapshot JSON NOT NULL DEFAULT (JSON_OBJECT()),
  unit_price NUMERIC(14,2) NOT NULL CHECK (unit_price >= 0),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  line_total NUMERIC(14,2) GENERATED ALWAYS AS (unit_price * quantity) STORED,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
  CONSTRAINT fk_order_items_variant_id FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_order_items_order ON order_items (order_id);

CREATE TABLE inventory_movements (
  id CHAR(36) PRIMARY KEY,
  variant_id CHAR(36) NOT NULL,
  order_id CHAR(36),
  movement_type VARCHAR(16) NOT NULL
    CHECK (movement_type IN ('IMPORT', 'RESERVE', 'RELEASE', 'SALE', 'RETURN', 'ADJUST')),
  quantity_delta INTEGER NOT NULL CHECK (quantity_delta <> 0),
  stock_balance INTEGER NOT NULL CHECK (stock_balance >= 0),
  reserved_balance INTEGER NOT NULL CHECK (reserved_balance >= 0),
  reason TEXT,
  idempotency_key VARCHAR(100) NOT NULL UNIQUE,
  created_by CHAR(36),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CHECK (stock_balance >= reserved_balance),
  CONSTRAINT fk_inventory_movements_variant_id FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE RESTRICT,
  CONSTRAINT fk_inventory_movements_order_id FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
  CONSTRAINT fk_inventory_movements_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_inventory_movements_variant_time
  ON inventory_movements (variant_id, created_at DESC);

-- ============================================================
-- Invoices, equipment, notifications, jobs and audit
-- ============================================================

CREATE TABLE invoices (
  id CHAR(36) PRIMARY KEY,
  invoice_number VARCHAR(40) NOT NULL UNIQUE,
  member_id CHAR(36),
  payment_id CHAR(36) NOT NULL UNIQUE,
  subtotal NUMERIC(14,2) NOT NULL CHECK (subtotal >= 0),
  tax NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (tax >= 0),
  discount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
  total NUMERIC(14,2) GENERATED ALWAYS AS (subtotal + tax - discount) STORED,
  currency CHAR(3) NOT NULL DEFAULT 'VND',
  status VARCHAR(12) NOT NULL DEFAULT 'DRAFT'
    CHECK (status IN ('DRAFT', 'ISSUED', 'PAID', 'VOID')),
  issued_at DATETIME(6),
  paid_at DATETIME(6),
  pdf_file_id CHAR(36),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CHECK (total >= 0),
  CHECK (issued_at IS NULL OR status IN ('ISSUED', 'PAID', 'VOID')),
  CONSTRAINT fk_invoices_member_id FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE SET NULL,
  CONSTRAINT fk_invoices_payment_id FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE RESTRICT,
  CONSTRAINT fk_invoices_pdf_file_id FOREIGN KEY (pdf_file_id) REFERENCES file_assets(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE equipment (
  id CHAR(36) PRIMARY KEY,
  branch_id CHAR(36),
  asset_code VARCHAR(40) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  category VARCHAR(80) NOT NULL,
  location VARCHAR(150),
  purchase_date DATE,
  warranty_until DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE', 'MAINTENANCE', 'OUT_OF_SERVICE', 'RETIRED')),
  notes TEXT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CHECK (warranty_until IS NULL OR purchase_date IS NULL OR warranty_until >= purchase_date),
  CONSTRAINT fk_equipment_branch_id FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_equipment_branch_status ON equipment (branch_id, status);

CREATE TABLE maintenance_records (
  id CHAR(36) PRIMARY KEY,
  equipment_id CHAR(36) NOT NULL,
  scheduled_at DATETIME(6) NOT NULL,
  started_at DATETIME(6),
  completed_at DATETIME(6),
  maintenance_type VARCHAR(80) NOT NULL,
  cost NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (cost >= 0),
  vendor VARCHAR(150),
  description TEXT,
  status VARCHAR(16) NOT NULL DEFAULT 'SCHEDULED'
    CHECK (status IN ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
  created_by CHAR(36),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  row_version INTEGER NOT NULL DEFAULT 1 CHECK (row_version > 0),
  CHECK (completed_at IS NULL OR started_at IS NOT NULL),
  CHECK (completed_at IS NULL OR completed_at >= started_at),
  CONSTRAINT fk_maintenance_records_equipment_id FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE RESTRICT,
  CONSTRAINT fk_maintenance_records_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_maintenance_equipment_status
  ON maintenance_records (equipment_id, status, scheduled_at);

CREATE TABLE notifications (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  notification_type VARCHAR(50) NOT NULL,
  title VARCHAR(180) NOT NULL,
  body TEXT NOT NULL,
  data JSON NOT NULL DEFAULT (JSON_OBJECT()),
  action_url TEXT,
  read_at DATETIME(6),
  email_status VARCHAR(16) NOT NULL DEFAULT 'NOT_REQUESTED'
    CHECK (email_status IN ('NOT_REQUESTED', 'PENDING', 'SENT', 'FAILED')),
  idempotency_key VARCHAR(120),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_notifications_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX uq_notifications_idempotency ON notifications (idempotency_key);
CREATE INDEX idx_notifications_user_unread
  ON notifications (user_id, read_at, created_at DESC);

CREATE TABLE background_jobs (
  id CHAR(36) PRIMARY KEY,
  external_job_id VARCHAR(100) UNIQUE,
  job_type VARCHAR(60) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED')),
  progress SMALLINT NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
  requested_by CHAR(36),
  parameters JSON NOT NULL DEFAULT (JSON_OBJECT()),
  result_file_id CHAR(36),
  error_message TEXT,
  started_at DATETIME(6),
  finished_at DATETIME(6),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CHECK (finished_at IS NULL OR started_at IS NOT NULL),
  CHECK (finished_at IS NULL OR finished_at >= started_at),
  CONSTRAINT fk_background_jobs_requested_by FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_background_jobs_result_file_id FOREIGN KEY (result_file_id) REFERENCES file_assets(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_background_jobs_status_created ON background_jobs (status, created_at);

CREATE TABLE audit_logs (
  id CHAR(36) PRIMARY KEY,
  actor_user_id CHAR(36),
  action VARCHAR(100) NOT NULL,
  entity_type VARCHAR(80) NOT NULL,
  entity_id CHAR(36),
  before_data JSON,
  after_data JSON,
  request_id CHAR(36),
  ip_address VARCHAR(45),
  user_agent TEXT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_audit_logs_actor_user_id FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX idx_audit_logs_entity ON audit_logs (entity_type, entity_id, created_at DESC);
CREATE INDEX idx_audit_logs_actor ON audit_logs (actor_user_id, created_at DESC);
CREATE INDEX idx_audit_logs_created ON audit_logs (created_at DESC);
